
import React from 'react';

interface LegalProps {
  type: 'privacy' | 'terms';
}

export const Legal: React.FC<LegalProps> = ({ type }) => {
  const isPrivacy = type === 'privacy';
  
  return (
    <div className="max-w-4xl mx-auto py-12 px-4">
      <div className="bg-white dark:bg-slate-800 p-8 md:p-12 rounded-3xl shadow-xl border border-slate-100 dark:border-slate-700">
        <h1 className="text-3xl font-black text-slate-900 dark:text-white mb-8 border-b pb-4">
          {isPrivacy ? 'Privacy Policy' : 'Terms of Service'}
        </h1>
        
        <div className="prose dark:prose-invert max-w-none text-slate-600 dark:text-slate-400 space-y-6 leading-relaxed">
          {isPrivacy ? (
            <>
              <p>Last updated: October 2025</p>
              <h2 className="text-xl font-bold text-slate-800 dark:text-white">1. Information We Collect</h2>
              <p>At ProBoost AI, we prioritize your data privacy. We collect minimal information required to provide our AI services, including your professional background data and contact email if provided during registration.</p>
              
              <h2 className="text-xl font-bold text-slate-800 dark:text-white">2. How We Use Your Data</h2>
              <p>Your data is used exclusively to generate the AI content you request (LinkedIn posts, resumes, profile rewrites). <strong>We do not sell your personal information to third parties.</strong></p>
              
              <h2 className="text-xl font-bold text-slate-800 dark:text-white">3. AI Training Policy</h2>
              <p>In our standard tiers, we utilize Google Gemini API. Your data processed through the API is subject to Google's Enterprise Privacy terms, which generally prohibit using customer data for global model training.</p>
              
              <h2 className="text-xl font-bold text-slate-800 dark:text-white">4. Cookies and Tracking</h2>
              <p>We use essential cookies to maintain your session and preferences. We do not use intrusive tracking or cross-site behavioral advertising pixels.</p>
            </>
          ) : (
            <>
              <p>Last updated: October 2025</p>
              <h2 className="text-xl font-bold text-slate-800 dark:text-white">1. Acceptance of Terms</h2>
              <p>By accessing ProBoost AI, you agree to abide by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using the service.</p>
              
              <h2 className="text-xl font-bold text-slate-800 dark:text-white">2. Use License</h2>
              <p>Permission is granted to use ProBoost AI's generation tools for professional and commercial use. You retain full ownership of the text content generated for your personal use.</p>
              
              <h2 className="text-xl font-bold text-slate-800 dark:text-white">3. Limitations</h2>
              <p>You may not use ProBoost AI to generate spam, hate speech, or content that violates LinkedIn's User Agreement. We reserve the right to terminate access for users who abuse the AI generation system.</p>
              
              <h2 className="text-xl font-bold text-slate-800 dark:text-white">4. Disclaimer</h2>
              <p>The content generated by AI is provided "as is". While we strive for accuracy, ProBoost AI does not guarantee the professional success, job placements, or specific engagement metrics resulting from the use of its tools.</p>
            </>
          )}
        </div>
      </div>
    </div>
  );
};
